# Generated by Django 4.2.6 on 2023-10-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("land", models.FloatField(default=0, verbose_name="زمین")),
                (
                    "landscaping",
                    models.FloatField(default=0, verbose_name="محوطه سازی"),
                ),
                (
                    "construction",
                    models.FloatField(default=0, verbose_name="ساختمان سازی"),
                ),
                ("machinery", models.FloatField(default=0, verbose_name="ماشین آلات")),
                ("facilities", models.FloatField(default=0, verbose_name="تاسیسات")),
                (
                    "transportation",
                    models.FloatField(default=0, verbose_name="وسایل حمل و نقل"),
                ),
                (
                    "office_equipment",
                    models.FloatField(default=0, verbose_name="وسایل اداری"),
                ),
                (
                    "raw_materials_packaging",
                    models.FloatField(
                        default=0, verbose_name="هزینه مواد اولیه و بسته بندی"
                    ),
                ),
                (
                    "salaries_wages",
                    models.FloatField(default=0, verbose_name="هزینه حقوق و دستمزد"),
                ),
                (
                    "energy_consumption",
                    models.FloatField(default=0, verbose_name="هزینه انرژی مصرفی"),
                ),
                (
                    "maintenance_repairs",
                    models.FloatField(default=0, verbose_name="هزینه تعمیر و نگهداری"),
                ),
                (
                    "annual_production",
                    models.FloatField(default=0, verbose_name="میزان تولید سالانه"),
                ),
                (
                    "unit_price",
                    models.FloatField(
                        default=0, verbose_name="قیمت فروش یک واحد محصول"
                    ),
                ),
            ],
        ),
    ]
